### ISSUE TITLE
property body does not exist on type 'Request'

### ISSUE THREAD

**Issue by manishtpatel** [types/npm-express#9] opened 2016-09-18 02:45 UTC
Trying to upgrade from dt~express to npm~express. Getting property body does not exist on type 'Request'. Am i doing anything wrong? or is it a bug?

**Comment by felixfbecker** [comment] 2016-09-18 03:31
Duplicate of #5 

The `body` attribute is not part of express, it is added by a middleware like https://github.com/types/npm-body-parser that you need to use explicitely.

**Closed as completed by felixfbecker** 2016-09-18 03:31 UTC
Labels: duplicate
